""""" VIM CONFIGURATION """""
"
    "source ~/.config/vim/plugin/startiy.vim
    "source ~/.config/vim/plugin/fzf.vim

    "My remaps
    let mapleader=" "
    nnoremap ; :
    nnoremap : ;
    nnoremap <BS> X
    nnoremap Y y$
    map <C-c> "+y
    nnoremap <leader>q ZQ
    nnoremap <leader><leader> :set relativenumber!<CR>
    nnoremap <leader>, :set nohlsearch<CR>
    noremap <leader>s :Startify<CR>
    noremap <leader>y :Yazi<CR>
    nnoremap <leader>w :so $MYVIMRC<CR>

    "Line down and up
    nnoremap <A-j> :m .+1<CR>
    nnoremap <A-k> :m .-2<CR>
    inoremap <A-j> <Esc>:m .+1<CR>gi
    inoremap <A-k> <Esc>:m .-2<CR>gi
    vnoremap <A-j> :m '>+1<CR>gv
    vnoremap <A-k> :m '<-2<CR>gv

    "Select all and sudo trick
    noremap <leader>a :normal! ggV$G$<CR>
    command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

    "Windows focus, rearrange and swap
    noremap <C-j> <C-w>j
    noremap <C-k> <C-w>k
    noremap <C-h> <C-w>h
    noremap <C-l> <C-w>l
    noremap <C-n> <C-w>w
    noremap <leader>r <C-w>r
    noremap <leader>l <C-w>L
    noremap <leader>h <C-w>H

    "Buffers prev, next, delete,show and new vertical split
    noremap <leader>b :bp<CR>
    noremap <leader>n :bn<CR>
    noremap <leader>x :bd<CR>
    nnoremap <leader><Tab> :buffer<Space><Tab>
    noremap <leader>v :vnew<CR>

    "Numbered list macro
    noremap <leader>c I0gvg
    
    "Optional settings
    set background=dark   
    colorscheme wildcharm
    syntax on
    filetype plugin indent on
    set nocompatible
    set autoread
    set backspace=indent,eol,start
    set cul
    set directory=~/Veřejné//
    set hidden
    set ignorecase smartcase
    set incsearch
    set laststatus=2
    set lazyredraw
    set mouse=a
    set number
    set pastetoggle=<F2>
    set ruler
    set scrolloff=2
    set showcmd
    set showmatch mat=2
    set showtabline=1
    set spelllang=cs,en
    " set softtabstop=4 shiftwidth=4 expandtab
    set wildcharm=<Tab>
    set wildmenu
    set wildoptions=pum,tagfile
    
    "Statusline
     hi StatusLine ctermbg=0 ctermfg=92
     set statusline=%n\ %f\ %m\ \ \ %v\ \ %l/%L%<%h%w%r\ \ \ %y
     set statusline+=%=reg\ {%{v:register}}\ \ 
    " set statusline=%f\ \%<\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P    "default vim

   "Plugins
   call plug#begin()
     " List your plugins here
     Plug 'tpope/vim-commentary'
     Plug 'mhinz/vim-startify'
     " Plug 'utubo/vim-registers-lite'
     Plug 'junegunn/vim-peekaboo'
     Plug 'LnL7/vim-nix'
     Plug 'chriszarate/yazi.vim'
     Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
     Plug 'junegunn/fzf.vim'
   call plug#end()


    "Cursor modes changes
        " Vertical bar in insert mode  
        let &t_SI = "\<Esc>[6 q"
        " Underline in replace mode
        let &t_SR = "\<Esc>[4 q"
        " Block in other modes
        let &t_EI = "\<Esc>[2 q"


    "Transparent background    
     hi Normal ctermbg=NONE
     hi NonText ctermbg=NONE
     hi LineNr ctermbg=NONE
    

     " Toggle background transparency
     let t:isTransparent = 0
     function! BGToggleTransparency()
       if t:isTransparent == 0
         hi Normal ctermbg=black
         set background=dark
         let t:isTransparent = 1
       else
          hi Normal ctermbg=NONE
          hi NonText ctermbg=NONE
          hi LineNr ctermbg=NONE
         let t:isTransparent = 0
       endif
     endfunction
     nnoremap <A-t> :call BGToggleTransparency()<CR>

""""" END OF FILE """""
